spring.application.name: splitwise-like
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080
logging:
    level:
        root: debug